[package]
name = "samloc"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.2"
bevy_renet = "1.0.0"
bincode = "1.3.3"
fastrand = "2.3.0"
rand = "0.9.0"
serde = "1.0.217"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"
